### ISSUE TITLE
bug: qmt is imported in the source files

### ISSUE THREAD

**Issue by basnijholt** [Microsoft/qmt#29]
This is definitely incorrect and currently only works because `qmt` is installed, running it from the repo will now not work.

**Comment by jgukelberger** [comment]
Bas, can you elaborate a little? You are not arguing that absolute imports within a package are incorrect, are you?

**Comment by basnijholt** [comment]
That is actually what I am saying, for example [here](https://github.com/Microsoft/qmt/blob/master/qmt/batchHarness.py#L11).

This should just something like `from . import Model`. 

Also the star imports in `__init__.py` are kind of bad style unless you define `__all__` in the modules.

**Comment by jgukelberger** [comment]
I agree that doing `import qmt` from a module inside the `qmt` package is weird. However, I don't think that extends to all absolute imports. E.g. `import qmt.Model` or `from qmt import Model` would be perfectly fine. Quoting PEP8:

> Absolute imports are recommended, as they are usually more readable and tend to be better behaved [...] However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose.

I don't think you can claim `from qmt import Model` to be unnecessarily verbose. Or did I misunderstand you?

Regarding star imports I tend to agree. So far things have just been small enough to effectively pull everything into the qmt namespace.

**Comment by basnijholt** [comment]
According to [Guido](https://mail.python.org/pipermail/python-dev/2010-October/104476.html) that part of PEP8 is outdated.

However, I initially thought that doing `import qmt` inside the pacakge would require you to have `qmt` somewhere in your `PYTHONPATH` and that it wouldn't work when you import `qmt` from the repo but I was wrong.

I thought that relative imports were the standard because it's used in all major packages I checked (numpy, scipy). But now I see that the [Python core devs](https://github.com/python/mypy/blob/master/mypy/api.py#L41) use absolute imports for inmodule imports too.

So I guess this issue can be closed ;)

**Comment by jgukelberger** [comment]
Closing as requested by the OP.
