### ISSUE TITLE
Fix build order in tasks

### ISSUE THREAD

**Issue by johnkgamble** [Microsoft/qmt#33]
The build order in the tasks branch is a bit weird now, and we need to be more careful since subtract lists are deprecated. We currently have:

[A,B,C] -> A overwrites B, overwrites C

However, if lithography is introduced into things, it's a little more complex:

[A,B,C,L1,L2] -> A,B,C builds as before, but then L1 and L2 are lithography layers on top.

This is a little goofy, since the lithography needs to come last (otherwise it complains about the base layers not being in place). However, non-lithographic layers listed last have lowest priority. I'd recommend reordering things so that they look like this:

[C,B,A,L1,L2],

where the overwrite precedence is left to write (so that L2 is highest priority and C is lowest). Does that makes sense? Would it be easy to do?

**Comment by donjan** [comment]
The examples in QMT have so far been in the order of deposition from ground up,
e.g. [substrate, wire, wire_Al_coating, wrapper_gates] and thus I always assumed
(non-litho or otherwise) objects listed first have lowest priority.

As such, [C,B,A,L1,L2] is what is currently implemented.

**Comment by johnkgamble** [comment]
OK, if I understand you correctly, it seems like this is not working as intended. For example:

```
substrate = Part3DData('substrate', 'Sketch001', 'extrude', 'dielectric',
                  material='SiO2', z0=-0.2, thickness=0.2, mesh_max_size=0.1)
air = Part3DData('air', 'Sketch001', 'extrude', 'dielectric',
                  material='air', z0=0.0, thickness=0.3, mesh_max_size=0.1)
 
wireLine = Part3DData('wireLine', 'Sketch', 'wire', 'semiconductor',
                  material='InAs', z0=0.0, thickness=0.1, mesh_max_size=0.04)
alCoating = Part3DData('alCoating', 'Sketch002', 'wire_shell', 'metal_gate',
                 material ='Al', target_wire=wireLine, depo_mode='depo', 
                 thickness=0.01, shell_verts=[1, 2],
                 boundary_condition={'voltage': 0.0})
oxide = Part3DData('oxide', 'Sketch003', 'lithography', 'dielectric',
                 material='HfO2', z0=0.0, thickness=0.010, layer_num=0, 
                 litho_base=[substrate, wireLine,alCoating], 
                 mesh_max_size=0.04)
leftGate = Part3DData('leftGate', 'Rectangle001_sketch', 'lithography', 'metal_gate',
                  material='Au', z0 =0.010, thickness=0.050, layer_num=1,
                  boundary_condition={'voltage': 1.0}, 
                  mesh_max_size=0.06)
rightGate = Part3DData('rightGate', 'Rectangle002_sketch', 'lithography', 'metal_gate',
                  material='Au', z0 =0.010, thickness=0.050, layer_num=1,
                  boundary_condition={'voltage': 1.0}, 
                  mesh_max_size=0.06)
 

build_order = [alCoating,wireLine,substrate,oxide,leftGate,rightGate, air]

freecad_dict = {
    'pyenv': python_2_env, # TODO
    'file_path': 'wire_test.FCStd',
    'params': {},
    'input_parts': build_order
}

geo_task = Geometry3D(options=freecad_dict)
```
This can be run with this [FreeCAD file](https://github.com/Microsoft/qmt/files/2389488/wire_test.FCStd.zip). Note that the build order

```
[alCoating,wireLine,substrate,oxide,leftGate,rightGate, air]
```

produces the correct result, but if I instead use 

```
[substrate, air,wireLine,alCoating,oxide,leftGate,rightGate]
```

the wire and coating are not written.

**Comment by donjan** [comment]
Correct, air is supposed to go last.
I was unclear about the usage of priority: leftmost objects get built first, and built objects don't get changed. Newly built objects fit around the existing ones, so leftmost means highest priority.
In fact your last line should (depending on the thickness of the air) produce a substrate and an air block, with the rest of the objects being empty.

This seems intuitive for me... is this what we want?

**Comment by johnkgamble** [comment]
Ohhhh, ok! Yes, I think this is a good convention, I just wasn't clear on it. Could you add some documentation / examples to the geo task? Then let's close it. Thanks!

**Comment by donjan** [comment]
Cleaned up the docstring for `Geometry3D`.
