### ISSUE TITLE
test_geo_task broken

### ISSUE THREAD

**Issue by johnkgamble** [Microsoft/qmt#37]
@donjan - it looks like test_geo_task broke in your latest patches. Does it run for you? I get a non-descriptive segfault now. 

It might have to do with that you removed my explicit setting of the python 2 environment in favor of something fancier? I have confirmed that rolling back past your changes fixes things. If we can't figure this out soon, please revert, as that test is a critical safety net. Thanks!

**Comment by donjan** [comment]
Yes it broke, but the exception it throws tells you how to fix it.
Unfortunately it's buried under other messages of failing unit tests. We should not have unit tests (e.g. comment them out) that are failing for longer stretches of time and not getting fixed.

How to fix it: run tests once, edit tests/host_settings/py2env to contain a valid Python2 path, rerun tests.
Please confirm that this works for you.
We can discuss the storage format of the current host settings.

**Comment by donjan** [comment]
OK, I see there is an additional error for test_geo_task specifically. Hold on.

**Comment by johnkgamble** [comment]
Are you running with the standard conda alenvironments or the docker container? All of the conda package versions are fine-tuned to avoid the conflicts you are talking about. I’ll check once I get to the office, but please make sure you’re using the standard test environment.

**Comment by johnkgamble** [comment]
Oh and also - the fenics-FreeCAD import and the warning was also there for a reason. There’s a weird modal thing that happens if they are imported out of order anywhere, in any namespace of a single interpreter. However, after they are imported in the correct order, either can be imported freely later.

**Comment by donjan** [comment]
As discussed, we seem to be good on the segfault.
