### ISSUE TITLE
QMS

### ISSUE THREAD

**Issue by whitewhim2718** [Microsoft/qmt#5]
I came across this repository and was reviewing the code. I notice the library `qms` is imported several times, but little documentation is provided. Would I be correct in assuming this is a proprietary Microsoft Python library for implementing ''quantum'' simulations in the Comsol? If so, is there a plan to open source this work?

Regards,
Thomas

**Comment by johnkgamble** [comment]
Hi Thomas,

Thanks for your interest! Yes, that's correct - `qms` is an internal package that we use to take models generated by `qmt` and simulate them using COMSOL. We left the references in to give users the idea of how to build an interface to their own simulation tool, but we don't have plans to release ours at this time.

Cheers,
John
